# Generated by Django 2.2.24 on 2021-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptFile', models.FileField(upload_to='scripting_file/')),
            ],
        ),
    ]
