# Generated by Django 2.2.24 on 2021-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcriptFile', models.FileField(upload_to='transcript_file/')),
            ],
        ),
    ]
