# Generated by Django 2.2.24 on 2021-06-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptingApp', '0002_transcript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
